# Generated by Django 5.2.17 on 2026-08-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Territorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, unique=True)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Território/ESF",
                "verbose_name_plural": "Territórios/ESF",
                "ordering": ["nome"],
            },
        ),
    ]
