# Generated by Django 5.2.17 on 2026-08-05 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("escolas", "0001_initial"),
        ("territorios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                ("acao", models.CharField(max_length=100)),
                ("objeto", models.CharField(max_length=200)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoria",
                "verbose_name_plural": "Logs de Auditoria",
                "ordering": ["-data_hora"],
            },
        ),
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "perfil",
                    models.CharField(
                        choices=[
                            ("educacao", "Educação"),
                            ("saude", "Saúde"),
                            ("gestao", "Gestão Municipal"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        blank=True,
                        help_text="Obrigatório para perfil Educação.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="escolas.escola",
                    ),
                ),
                (
                    "territorio_esf",
                    models.ForeignKey(
                        blank=True,
                        help_text="Território/ESF de referência (perfil Saúde). Deixe em branco se este profissional acompanha todas as escolas/territórios.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="territorios.territorio",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuário",
                "verbose_name_plural": "Perfis de Usuário",
            },
        ),
    ]
