# Generated by Django 5.2.17 on 2026-08-15 23:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="logauditoria",
            index=models.Index(
                fields=["usuario", "-data_hora"], name="usuarios_lo_usuario_fd0585_idx"
            ),
        ),
    ]
