# Generated by Django 5.2.17 on 2026-08-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Escola",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("municipal_ef", "Municipal - Ensino Fundamental"),
                            ("municipal_ei", "Municipal - Educação Infantil"),
                            ("estadual", "Estadual"),
                            ("especial", "Educação Especial"),
                        ],
                        default="municipal_ef",
                        max_length=20,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Escola",
                "verbose_name_plural": "Escolas",
                "ordering": ["nome"],
            },
        ),
    ]
