# Generated by Django 5.2.17 on 2026-08-05 16:11

import django.db.models.deletion
import estudantes.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("escolas", "0001_initial"),
        ("territorios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estudante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "nome",
                    models.CharField(
                        max_length=200, verbose_name="Nome da Criança ou Adolescente"
                    ),
                ),
                (
                    "cpf",
                    estudantes.fields.CPFCriptografadoField(
                        max_length=400, verbose_name="CPF"
                    ),
                ),
                (
                    "cpf_hash",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="Data de Nascimento"),
                ),
                (
                    "nome_responsavel",
                    models.CharField(
                        max_length=200, verbose_name="Nome do Responsável"
                    ),
                ),
                ("telefone", models.CharField(max_length=20)),
                (
                    "ano_turma",
                    models.CharField(max_length=50, verbose_name="Ano/Turma"),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estudantes",
                        to="escolas.escola",
                    ),
                ),
                (
                    "territorio_esf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estudantes",
                        to="territorios.territorio",
                        verbose_name="Território/ESF de referência",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estudante",
                "verbose_name_plural": "Estudantes",
                "ordering": ["nome"],
            },
        ),
    ]
