# Generated by Django 5.2.17 on 2026-08-15 23:49

import estudantes.fields
import estudantes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudantes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudante",
            name="cpf",
            field=estudantes.fields.CPFCriptografadoField(
                max_length=400,
                validators=[estudantes.validators.validar_cpf],
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="estudante",
            name="telefone",
            field=models.CharField(
                max_length=20, validators=[estudantes.validators.validar_telefone]
            ),
        ),
    ]
