# Generated by Django 5.2.17 on 2026-08-05 17:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("atendimentos", "0001_initial"),
        ("estudantes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Caso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "data_encaminhamento",
                    models.DateField(verbose_name="Data do Encaminhamento"),
                ),
                (
                    "profissional_responsavel",
                    models.CharField(
                        max_length=150,
                        verbose_name="Profissional Responsável (Educação)",
                    ),
                ),
                (
                    "data_atendimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Atendimento"
                    ),
                ),
                (
                    "retorno_previsto",
                    models.DateField(
                        blank=True, null=True, verbose_name="Retorno Previsto"
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("aguardando", "Aguardando Atendimento"),
                            ("em_acompanhamento", "Em Acompanhamento"),
                            ("encerrado", "Encerrado"),
                        ],
                        default="aguardando",
                        max_length=20,
                    ),
                ),
                (
                    "gravidade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="media",
                        help_text="Prioridade clínica/administrativa avaliada pelos profissionais, independente do tempo de espera.",
                        max_length=10,
                        verbose_name="Gravidade do Caso",
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                (
                    "anexo_encaminhamento",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="encaminhamentos/%Y/%m/",
                        verbose_name="Anexo do Encaminhamento (PDF)",
                    ),
                ),
                (
                    "estudante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="casos",
                        to="estudantes.estudante",
                    ),
                ),
                (
                    "servico_encaminhado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="casos",
                        to="atendimentos.tipoatendimento",
                        verbose_name="Serviço Encaminhado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caso / Encaminhamento",
                "verbose_name_plural": "Casos / Encaminhamentos",
                "ordering": ["-data_registro"],
            },
        ),
        migrations.CreateModel(
            name="Evolucao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_movimentacao",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("servico_responsavel", models.CharField(max_length=150)),
                ("profissional_responsavel", models.CharField(max_length=150)),
                ("acao_realizada", models.TextField()),
                ("encaminhamento_efetuado", models.TextField(blank=True)),
                ("retorno_recebido", models.TextField(blank=True)),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evolucoes",
                        to="casos.caso",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evolução do Caso",
                "verbose_name_plural": "Evoluções do Caso",
                "ordering": ["-data_movimentacao", "-criado_em"],
            },
        ),
    ]
