# Generated by Django 5.2.17 on 2026-08-15 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("casos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caso",
            name="anexo_encaminhamento",
            field=models.FileField(
                blank=True,
                help_text="Apenas arquivos PDF. Atenção: em produção na Vercel isso ainda não tem armazenamento persistente configurado — ver CHANGELOG.md.",
                null=True,
                upload_to="encaminhamentos/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="Anexo do Encaminhamento (PDF)",
            ),
        ),
        migrations.AlterField(
            model_name="caso",
            name="gravidade",
            field=models.CharField(
                choices=[
                    ("baixa", "Baixa"),
                    ("media", "Média"),
                    ("alta", "Alta"),
                    ("urgente", "Urgente"),
                ],
                db_index=True,
                default="media",
                help_text="Prioridade clínica/administrativa avaliada pelos profissionais, independente do tempo de espera.",
                max_length=10,
                verbose_name="Gravidade do Caso",
            ),
        ),
        migrations.AlterField(
            model_name="caso",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("aguardando", "Aguardando Atendimento"),
                    ("em_acompanhamento", "Em Acompanhamento"),
                    ("encerrado", "Encerrado"),
                ],
                db_index=True,
                default="aguardando",
                max_length=20,
            ),
        ),
    ]
